/*
 * Copyright 2019 Mark Scott
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.codebrewer.fr24feedprocessor.basestation.domain;

/**
 * The transmission message types generated by BaseStation.
 *
 * <p>Based on information from http://woodair.net/sbs/Article/Barebones42_Socket_Data.htm
 */
public enum TransmissionType {
  // Order is important: the ordinal value is one less than the value that
  // appears in CSV-formatted messages
  //
  IDENTIFICATION_AND_CATEGORY,
  SURFACE_POSITION,
  AIRBORNE_POSITION,
  AIRBORNE_VELOCITY,
  SURVEILLANCE_ALTITUDE,
  SURVEILLANCE_ID,
  AIR_TO_AIR,
  ALL_CALL_REPLY;

  /**
   * Returns the value of this enum having the ordinal one less than the given raw value.
   *
   * @param rawValue a transmission message type value from an incoming message; null or a value
   * outside the range 1 to 8 returns null
   *
   * @return the value of this enum having the ordinal one less than the given raw value, or null
   */
  public static TransmissionType getByRawValue(Short rawValue) {
    return rawValue == null || rawValue < 1 || rawValue > values().length ? null
                                                                          : values()[rawValue - 1];
  }
}
